{% set version = "0.1.5" %}

package:
  name: pymagewell
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pymagewell/pymagewell-{{ version }}.tar.gz
    sha256: 1eb5d21419424f16c7d3872bb28dd681f5b243c72130c7b01a9f6a3f52320460
  - url: https://github.com/KCL-BMEIS/pymagewell/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6f7f9c3e438866e6ee7390acede4dd8e4c3bfb7f1370deb4d577b203820f943e
    folder: test-data

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or linux or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - numpy >=1.21.4
    - pywin32 >=304  # [win]
    - python
    - libopencv >=4.5.5
    - opencv >=4.5.5
    - py-opencv >=4.5.5
test:
  imports:
    - mwcapture
    - pymagewell
  requires:
    - pip
    - pytest
  source_files:
    - test-data/src/tests
  commands:
    - pip check
    - pytest  # [win]

about:
  home: https://github.com/KCL-BMEIS/pymagewell
  summary: Python library for interfacing with Magewell ProCapture frame grabbers
  description: |
    pymagewell is a Python library for interfacing with Magewell ProCapture frame grabbers. It is based on (and includes) Magewell's Windows SDK and is therefore Windows only. However, it provides a mock class for testing and development that does not depend on the SDK's Windows .dll files, so pymagwell can also be installed on macOS and Linux.
  doc_url: https://kcl-bmeis.github.io/pymagewell/
  dev_url: https://github.com/KCL-BMEIS/pymagewell
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crnbaker
