{% set version = "0.1.4" %}

package:
  name: pymagewell
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pymagewell/pymagewell-{{ version }}.tar.gz
    sha256: 248a1b7a6bb90e7caf68dde832b85064771641c326179f2600c99ca4b8527659
  - url: https://github.com/KCL-BMEIS/pymagewell/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d89dd46c7db9fda9a8df313ec2c715523b3b4af47c03d1cc7b65c8f652c6aa4c
    folder: test-data

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or linux or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - numpy >=1.21.4
    - pywin32 >=303  # [win]
    - python
    - libopencv >=4.5.5
    - opencv >=4.5.5
    - py-opencv >=4.5.5
test:
  imports:
    - mwcapture
    - pymagewell
  requires:
    - pip
    - pytest
  source_files:
    - test-data/tests
  commands:
    - pip check
    - pytest  # [win]

about:
  home: https://github.com/KCL-BMEIS/pymagewell
  summary: Python library for interfacing with Magewell ProCapture frame grabbers
  description: |
    pymagewell is a Python library for interfacing with Magewell ProCapture frame grabbers. It is based on (and includes) Magewell's Windows SDK and is therefore Windows only. However, it provides a mock class for testing and development that does not depend on the SDK's Windows .dll files, so pymagwell can also be installed on macOS and Linux.
  doc_url: https://kcl-bmeis.github.io/pymagewell/
  dev_url: https://github.com/KCL-BMEIS/pymagewell
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crnbaker
