{% set version = "0.1.3" %}

package:
  name: pymagewell 
  version: {{ version }} 

source:
  - url: https://pypi.io/packages/source/p/pymagewell/pymagewell-{{ version }}.tar.gz  
    sha256: bc906d1c5c70146d4131ff8932d969279c2a97f3f8d8792ba6093b2b1bd972c9
  - url: https://github.com/KCL-BMEIS/pymagewell/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 4ec8822a0a4816c515a521ddc9b1f74f4464b12414fcfffa4dc2a102a44c2629
    folder: test-data

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<39 or linux or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - numpy >=1.21.4
    - pywin32 >=303  # [win]
    - python
    - libopencv >=4.5.5
    - opencv >=4.5.5
    - py-opencv >=4.5.5
test:
  imports:
    - mwcapture
    - pymagewell
  requires:
    - pip
    - pytest
  source_files:
    - test-data/tests
  commands:
    - pip check
    - pytest  # [win]

about:
  home: https://github.com/KCL-BMEIS/pymagewell
  summary: Python library for interfacing with Magewell ProCapture frame grabbers 
  description: |
    pymagewell is a Python library for interfacing with Magewell ProCapture frame grabbers. It is based on (and includes) Magewell's Windows SDK and is therefore Windows only. However, it provides a mock class for testing and development that does not depend on the SDK's Windows .dll files, so pymagwell can also be installed on macOS and Linux.
  doc_url: https://kcl-bmeis.github.io/pymagewell/
  dev_url: https://github.com/KCL-BMEIS/pymagewell
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crnbaker
